"""REST endpoint: automated SRE incident post-mortem export (Markdown and JSON)."""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query, Response, status
from fastapi.responses import JSONResponse

from app.services.groq_client import render_agentic_post_mortem
from app.services.incident_log import incident_log

router = APIRouter(tags=["incident"])


@router.get("/incident/post-mortem", summary="Export an incident post-mortem report")
async def get_post_mortem(
    token: str | None = Query(default=None, description="Confirmation token identifying the incident. Defaults to the most recently resolved incident."),
    format: str = Query(default="json", pattern="^(json|markdown)$", description="Output format: 'json' or 'markdown'."),
) -> Response:
    """Return a detailed SRE incident report: timeline, triggering alert, remediation command,
    actor, confirmation token, and Mean Time To Resolution (MTTR).

    When `GROQ_API_KEY` is configured, the Markdown body is generated by a Llama-3 agentic
    RCA model; otherwise it falls back to the deterministic template. Pending (unconfirmed or
    dry-run-only) incidents are not eligible for export until they are actually executed.
    """
    record = incident_log.get(token) if token is not None else incident_log.latest_resolved()
    if record is None or record.resolved_at is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="No resolved incident found for export.")

    markdown, ai_generated = await render_agentic_post_mortem(record)

    if format == "markdown":
        return Response(
            content=markdown,
            media_type="text/markdown",
            headers={"Content-Disposition": f'attachment; filename="post-mortem-{record.token}.md"'},
        )

    payload = record.model_dump(mode="json")
    payload["markdown"] = markdown
    payload["ai_generated"] = ai_generated
    return JSONResponse(content=payload)
