"""Integration and unit tests for the enterprise Layer-3 features: Groq agentic post-mortems and Discord alerts."""

from __future__ import annotations

import logging
from types import SimpleNamespace

import httpx
import pytest
from fastapi.testclient import TestClient
from pydantic import SecretStr

from app.schemas.command import ExecutionResult, IntentType, ParsedCommand
from app.services import discord_alerts, groq_client
from app.services.incident_log import incident_log


def _resolved_record():
    """Open and resolve an incident record, returning it for use in tests."""
    command = ParsedCommand(
        raw_text="kill payment-gateway-pod",
        intent=IntentType.PROCESS_KILL,
        target_process_name="payment-gateway-pod",
        language="en",
    )
    record = incident_log.open_incident("enterprise-token", command, "K8S_CLUSTER")
    result = ExecutionResult(
        success=True,
        intent=IntentType.PROCESS_KILL,
        message="Restarted pod 'payment-gateway-pod'. Anomaly cleared; metrics have recovered.",
        dry_run=False,
        affected_process_name="payment-gateway-pod",
    )
    return incident_log.resolve_incident("enterprise-token", result)


def _settings_with(groq_key: str | None = None, discord_url: str | None = None) -> SimpleNamespace:
    """Return a settings-like object with the requested integration keys."""
    return SimpleNamespace(
        GROQ_API_KEY=SecretStr(groq_key) if groq_key is not None else None,
        GROQ_MODEL="llama3-8b-8192",
        DISCORD_WEBHOOK_URL=discord_url,
        DISCORD_ALERTS_ENABLED=True,
    )


def _fake_groq_factory(content: str):
    """Return a fake AsyncGroq callable that yields a chat completion with the supplied content."""
    def _fake(api_key: str):
        async def _create(**kwargs):
            return SimpleNamespace(
                choices=[SimpleNamespace(message=SimpleNamespace(content=content))]
            )

        return SimpleNamespace(chat=SimpleNamespace(completions=SimpleNamespace(create=_create)))

    return _fake


@pytest.mark.asyncio
async def test_groq_client_returns_none_when_key_missing() -> None:
    """Without a Groq API key the agentic generator should short-circuit and return None."""
    record = _resolved_record()
    monkeypatch = pytest.MonkeyPatch()
    monkeypatch.setattr(groq_client, "get_settings", lambda: _settings_with(groq_key=None))
    try:
        report = await groq_client.generate_groq_post_mortem(record)
        assert report is None
    finally:
        monkeypatch.undo()


@pytest.mark.asyncio
async def test_groq_client_generates_markdown_when_key_present(monkeypatch: pytest.MonkeyPatch) -> None:
    """When a Groq key is present the agentic report should be returned."""
    record = _resolved_record()
    monkeypatch.setattr(groq_client, "get_settings", lambda: _settings_with(groq_key="test-key"))
    monkeypatch.setattr(groq_client, "AsyncGroq", _fake_groq_factory("# AI-Generated Post-Mortem\n\nRCA generated by Groq."))

    report = await groq_client.generate_groq_post_mortem(record)

    assert report is not None
    assert "AI-Generated Post-Mortem" in report


@pytest.mark.asyncio
async def test_groq_client_falls_back_on_api_error(monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture) -> None:
    """Any Groq exception must be logged and return None so the endpoint can fall back."""
    record = _resolved_record()
    monkeypatch.setattr(groq_client, "get_settings", lambda: _settings_with(groq_key="test-key"))
    monkeypatch.setattr(groq_client, "AsyncGroq", lambda api_key: (_ for _ in ()).throw(RuntimeError("groq failure")))

    with caplog.at_level(logging.WARNING, logger="app.services.groq_client"):
        report = await groq_client.generate_groq_post_mortem(record)

    assert report is None
    assert "Groq post-mortem generation failed" in caplog.text


@pytest.mark.asyncio
async def test_render_agentic_post_mortem_flags_ai_generated(monkeypatch: pytest.MonkeyPatch) -> None:
    """render_agentic_post_mortem must surface whether the report came from Groq."""
    record = _resolved_record()
    monkeypatch.setattr(groq_client, "get_settings", lambda: _settings_with(groq_key="test-key"))
    monkeypatch.setattr(groq_client, "AsyncGroq", _fake_groq_factory("# Groq Report"))

    markdown, ai_generated = await groq_client.render_agentic_post_mortem(record)

    assert ai_generated is True
    assert "Groq Report" in markdown


@pytest.mark.asyncio
async def test_render_agentic_post_mortem_uses_fallback_when_unconfigured(monkeypatch: pytest.MonkeyPatch) -> None:
    """If no Groq key is configured the deterministic template should be returned."""
    record = _resolved_record()
    monkeypatch.setattr(groq_client, "get_settings", lambda: _settings_with(groq_key=None))

    markdown, ai_generated = await groq_client.render_agentic_post_mortem(record)

    assert ai_generated is False
    assert "# Incident Post-Mortem" in markdown


def test_discord_build_payload_contains_required_fields() -> None:
    """The Discord embed must contain the resolved incident fields and sub-second MTTR."""
    record = _resolved_record()
    record.mttr_seconds = 0.42
    payload = discord_alerts._build_payload(record)

    assert payload["embeds"][0]["title"] == "🚨 CRITICAL INCIDENT RESOLVED"
    assert any(field["name"] == "Executed Command" for field in payload["embeds"][0]["fields"])
    assert any(field["name"] == "Mitigated Target" for field in payload["embeds"][0]["fields"])
    assert any("0.420s (sub-second)" in field["value"] for field in payload["embeds"][0]["fields"])


@pytest.mark.asyncio
async def test_discord_alert_noops_without_webhook_url(monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture) -> None:
    """With no webhook URL, send_resolution_alert must do nothing and not raise."""
    record = _resolved_record()
    monkeypatch.setattr(discord_alerts, "get_settings", lambda: _settings_with(discord_url=None))

    with caplog.at_level(logging.WARNING, logger="app.services.discord_alerts"):
        await discord_alerts.send_resolution_alert(record)

    assert caplog.text == ""


@pytest.mark.asyncio
async def test_discord_alert_sends_when_webhook_configured(monkeypatch: pytest.MonkeyPatch) -> None:
    """A configured webhook URL must be POSTed with the JSON payload."""
    record = _resolved_record()
    calls = []
    monkeypatch.setattr(discord_alerts, "get_settings", lambda: _settings_with(discord_url="https://discord.example/webhook"))

    class _FakeResponse:
        raise_for_status = lambda self: None

    class _FakeClient:
        def __init__(self, **kwargs) -> None:
            pass

        async def post(self, url: str, json: dict | None = None) -> _FakeResponse:
            calls.append((url, json))
            return _FakeResponse()

        async def __aenter__(self):
            return self

        async def __aexit__(self, exc_type, exc, tb) -> None:
            return None

    fake_httpx = SimpleNamespace(AsyncClient=_FakeClient)
    monkeypatch.setattr(discord_alerts, "httpx", fake_httpx)

    await discord_alerts.send_resolution_alert(record)

    assert len(calls) == 1
    assert calls[0][0] == "https://discord.example/webhook"
    assert calls[0][1]["embeds"][0]["title"] == "🚨 CRITICAL INCIDENT RESOLVED"


@pytest.mark.asyncio
async def test_discord_alert_logs_and_swallows_http_errors(monkeypatch: pytest.MonkeyPatch, caplog: pytest.LogCaptureFixture) -> None:
    """A failing HTTP request must be logged and not propagate."""
    record = _resolved_record()
    monkeypatch.setattr(discord_alerts, "get_settings", lambda: _settings_with(discord_url="https://discord.example/webhook"))

    class _FailingClient:
        def __init__(self, **kwargs) -> None:
            pass

        async def post(self, **kwargs) -> None:
            raise httpx.ConnectError("simulated network loss")

        async def __aenter__(self):
            return self

        async def __aexit__(self, exc_type, exc, tb) -> None:
            return None

    fake_httpx = SimpleNamespace(AsyncClient=_FailingClient)
    monkeypatch.setattr(discord_alerts, "httpx", fake_httpx)

    with caplog.at_level(logging.WARNING, logger="app.services.discord_alerts"):
        await discord_alerts.send_resolution_alert(record)

    assert "Discord webhook alert failed" in caplog.text


def test_confirm_endpoint_triggers_discord_alert_on_success(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    """A successful, real confirmation should schedule a Discord resolution alert."""
    from app.core.security import confirmation_registry
    from app.services import system_engine

    command = ParsedCommand(
        raw_text="kill payment-gateway-pod",
        intent=IntentType.PROCESS_KILL,
        target_process_name="payment-gateway-pod",
        language="en",
        requires_confirmation=True,
    )
    pending = confirmation_registry.register(command, mode="K8S_CLUSTER")
    incident_log.open_incident(pending.token, command, "K8S_CLUSTER")

    alerts = []

    async def _capture_alert(r):
        alerts.append(r)

    monkeypatch.setattr(discord_alerts, "send_resolution_alert", _capture_alert)

    async def _fake_cluster_execute(intent, target_name, dry_run=False):
        return ExecutionResult(
            success=True,
            intent=intent,
            message=f"Restarted pod '{target_name}'.",
            dry_run=dry_run,
            affected_process_name=target_name,
        )

    monkeypatch.setattr(system_engine, "cluster_execute", _fake_cluster_execute)

    response = client.post("/api/v1/commands/confirm", json={"token": pending.token, "dry_run": False})

    assert response.status_code == 200
    assert len(alerts) == 1
    assert alerts[0].token == pending.token


def test_confirm_endpoint_does_not_trigger_discord_on_dry_run(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    """A dry-run confirmation should not dispatch a Discord alert."""
    from app.core.security import confirmation_registry
    from app.services import system_engine

    command = ParsedCommand(
        raw_text="kill payment-gateway-pod",
        intent=IntentType.PROCESS_KILL,
        target_process_name="payment-gateway-pod",
        language="en",
        requires_confirmation=True,
    )
    pending = confirmation_registry.register(command, mode="K8S_CLUSTER")
    incident_log.open_incident(pending.token, command, "K8S_CLUSTER")

    alerts = []

    async def _capture_alert(r):
        alerts.append(r)

    monkeypatch.setattr(discord_alerts, "send_resolution_alert", _capture_alert)

    async def _fake_cluster_execute(intent, target_name, dry_run=False):
        return ExecutionResult(success=True, intent=intent, message="preview", dry_run=dry_run, affected_process_name=target_name)

    monkeypatch.setattr(system_engine, "cluster_execute", _fake_cluster_execute)

    response = client.post("/api/v1/commands/confirm", json={"token": pending.token, "dry_run": True})

    assert response.status_code == 200
    assert len(alerts) == 0


def test_post_mortem_endpoint_mark_enterprise_flags(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    """JSON post-mortem export should include ai_generated and markdown when Groq is mocked."""
    command = ParsedCommand(
        raw_text="kill payment-gateway-pod",
        intent=IntentType.PROCESS_KILL,
        target_process_name="payment-gateway-pod",
        language="en",
    )
    incident_log.open_incident("groq-token", command, "K8S_CLUSTER")
    incident_log.resolve_incident(
        "groq-token",
        ExecutionResult(success=True, intent=IntentType.PROCESS_KILL, message="Recovered.", dry_run=False, affected_process_name="payment-gateway-pod"),
    )
    monkeypatch.setattr(groq_client, "get_settings", lambda: _settings_with(groq_key="test-key"))
    monkeypatch.setattr(groq_client, "AsyncGroq", _fake_groq_factory("# Groq Report\n\nRCA."))

    response = client.get("/api/v1/incident/post-mortem", params={"token": "groq-token"})

    assert response.status_code == 200
    body = response.json()
    assert body["ai_generated"] is True
    assert "Groq Report" in body["markdown"]


def test_post_mortem_endpoint_uses_fallback_when_groq_unconfigured(client: TestClient, monkeypatch: pytest.MonkeyPatch) -> None:
    """When Groq is unconfigured the endpoint should still return a deterministic Markdown report."""
    command = ParsedCommand(raw_text="kill payment-gateway-pod", intent=IntentType.PROCESS_KILL, target_process_name="payment-gateway-pod", language="en")
    incident_log.open_incident("fallback-token", command, "K8S_CLUSTER")
    incident_log.resolve_incident(
        "fallback-token",
        ExecutionResult(success=True, intent=IntentType.PROCESS_KILL, message="Recovered.", dry_run=False, affected_process_name="payment-gateway-pod"),
    )
    monkeypatch.setattr(groq_client, "get_settings", lambda: _settings_with(groq_key=None))

    response = client.get("/api/v1/incident/post-mortem", params={"token": "fallback-token"})

    assert response.status_code == 200
    body = response.json()
    assert body["ai_generated"] is False
    assert "# Incident Post-Mortem" in body["markdown"]
